import { useEffect, useState, type FormEvent } from 'react'
import { adminApi, contestApi, type AuditLog } from '../services/api'
import type { Contest, Tournament } from '../types'
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState } from './ui'

const formatDate = (value?: string) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—'
const tone = (status?: string) => status === 'LIVE' ? 'red' : status === 'FINISHED' ? 'green' : 'blue'

export const AdminContests = ({ tournament }: { tournament: Tournament }) => {
  const [contests, setContests] = useState<Contest[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = () => { setLoading(true); contestApi.list(tournament._id).then(({ contests: rows }) => setContests(rows)).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)) }
  useEffect(load, [tournament._id])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const round = String(form.get('round')); const matchNumber = form.get('matchNumber'); setBusy(true); setError(''); setNotice(''); try { await contestApi.create(tournament._id, { name: String(form.get('name')), round, group: round === 'GROUP_STAGE' ? String(form.get('group')) : undefined, matchNumber: round === 'GROUP_STAGE' ? undefined : Number(matchNumber), codeforcesContestId: Number(form.get('codeforcesContestId')), codeforcesUrl: String(form.get('codeforcesUrl')), startTime: String(form.get('startTime')), durationMinutes: Number(form.get('durationMinutes')) }); event.currentTarget.reset(); setNotice('Contest attached successfully.'); load() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to attach contest') } finally { setBusy(false) } }
  const sync = async (contest: Contest) => { setBusy(true); setError(''); try { const result = await contestApi.sync(tournament._id, contest._id); setNotice(`Synchronized ${result.results.length} results; ${result.unmatchedHandles.length} unmatched handles.`); load() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to synchronize results') } finally { setBusy(false) } }
  return <><Card><small>ATTACH CODEFORCES CONTEST</small><form className="contest-form" onSubmit={submit}><input required name="name" placeholder="Contest Name" /><select required name="round" defaultValue="GROUP_STAGE"><option value="GROUP_STAGE">Group Stage</option><option value="QUARTER_FINAL">Quarter Final</option><option value="SEMI_FINAL">Semi Final</option><option value="FINAL">Grand Final</option></select><select name="group" defaultValue="A"><option value="A">Group A</option><option value="B">Group B</option><option value="C">Group C</option><option value="D">Group D</option></select><input min="1" name="matchNumber" type="number" placeholder="Match number (knockout)" /><input required min="1" name="codeforcesContestId" type="number" placeholder="Codeforces Contest ID" /><input required name="codeforcesUrl" type="url" placeholder="Codeforces URL" /><input required name="startTime" type="datetime-local" /><input required min="1" name="durationMinutes" type="number" placeholder="Duration (minutes)" /><Button disabled={busy} type="submit">{busy ? 'Attaching...' : 'Attach Contest'}</Button></form>{error && <ErrorState error={error} />}{notice && <p className="admin-message">{notice}</p>}</Card><Card className="table-card">{loading ? <LoadingState label="Loading contests..." /> : <div className="table-wrap"><table><thead><tr><th>Contest</th><th>Round</th><th>Status</th><th>Last Synced</th><th /></tr></thead><tbody>{contests.length ? contests.map((contest) => <tr key={contest._id}><td><strong>{contest.name}</strong></td><td>{contest.group ? `Group ${contest.group}` : `${contest.round} M${contest.matchNumber || ''}`}</td><td><Badge tone={tone(contest.status) as 'blue'}>{contest.status}</Badge></td><td>{formatDate(contest.lastSyncedAt)}</td><td><Button disabled={busy} onClick={() => sync(contest)}>Sync Results</Button></td></tr>) : <tr><td colSpan={5}><EmptyState label="No contests attached yet." /></td></tr>}</tbody></table></div>}</Card></>
}

export const AdminLogs = ({ tournamentId }: { tournamentId: string }) => {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { adminApi.logs(tournamentId).then(({ logs: rows }) => setLogs(rows)).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)) }, [tournamentId])
  if (loading) return <LoadingState label="Loading system logs..." />
  if (error) return <ErrorState error={error} />
  if (!logs.length) return <EmptyState label="No recorded admin actions yet." />
  return <Card className="table-card"><div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Action</th><th>Admin</th><th>Description</th></tr></thead><tbody>{logs.map((log) => <tr key={log._id}><td>{formatDate(log.createdAt)}</td><td><Badge>{log.action}</Badge></td><td>{log.admin?.username || log.admin?.name || '—'}</td><td>{log.description}</td></tr>)}</tbody></table></div></Card>
}
