import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Crown, ExternalLink, Radio, Trophy, Users } from 'lucide-react'
import { AuthProvider, useAuth } from './context/AuthContext'
import { contestApi, tournamentApi, type Bracket, type TournamentEntry } from './services/api'
import type { Contest, LeaderboardEntry, Participant, Result, Tournament } from './types'
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState } from './components/ui'
import { DashboardLayout, Navbar } from './components/layout'
import { AdminContests, AdminLogs } from './components/admin'
import './App.css'

const useTournament = () => {
  const [tournament, setTournament] = useState<Tournament | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { tournamentApi.list().then(({ tournaments }) => setTournament(tournaments[0] || null)).catch((err: Error) => setError(err.message)).finally(() => setLoading(false)) }, [])
  return { tournament, loading, error, setTournament }
}
const PageState = ({ loading, error, empty, children }: { loading: boolean; error: string; empty?: boolean; children: ReactNode }) => loading ? <LoadingState /> : error ? <ErrorState error={error} /> : empty ? <EmptyState label="No tournament has been created yet." /> : <>{children}</>
const formatDate = (value?: string) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'TBA'
const statusTone = (status?: string) => status === 'LIVE' ? 'red' : status === 'FINISHED' || status === 'CHAMPION' ? 'green' : status === 'COMPLETED' ? 'gold' : 'blue'

function Home() {
  const { tournament, loading, error } = useTournament()
  return <><Navbar /><main className="home"><PageState loading={loading} error={error} empty={!tournament}><section className="hero-panel"><div><Badge tone="blue">CHAMPIONSHIP SERIES</Badge><h1>CODE ARENA <span>2026</span></h1><p>Where Code Meets Competition.</p><div className="hero-actions"><Link className="button" to="/register">Register Now <ArrowRight size={16} /></Link><Link className="button secondary" to="/bracket">Explore Bracket</Link></div></div><div className="countdown"><small>NEXT ROUND IN</small><div className="timer"><b>00<em>Days</em></b><b>00<em>Hours</em></b><b>00<em>Minutes</em></b><b>00<em>Seconds</em></b></div><Badge tone={statusTone(tournament?.status) as 'blue'}>{tournament?.status}</Badge></div></section><section className="section"><div className="section-title"><span>TOURNAMENT PATH</span><small>THE ROAD TO THE CROWN</small></div><div className="path">{['Group Stage', 'Quarter Final', 'Semi Final', 'Grand Final', 'Champion'].map((stage, index) => <div className="path-step" key={stage}><span>STAGE {index + 1}</span><strong>{stage}</strong></div>)}</div></section><section className="reward-row"><Card><Trophy color="#FFD700" /><div><small>CHAMPIONSHIP</small><strong>One competitor earns the crown.</strong></div></Card><Card><Users color="#2979FF" /><div><small>FIELD</small><strong>20 elite programmers. One arena.</strong></div></Card></section></PageState></main></>
}

function AuthPage({ register = false }: { register?: boolean }) {
  const { user, login, register: registerAccount } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to="/dashboard" replace />
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { if (register) await registerAccount({ name: String(form.get('name')), username: String(form.get('username')), email: String(form.get('email')), password: String(form.get('password')), codeforcesUsername: String(form.get('codeforcesUsername')) }); else await login(String(form.get('email')), String(form.get('password'))); navigate('/dashboard') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to authenticate') } finally { setBusy(false) } }
  return <div className="auth-page"><Link className="brand" to="/"><span className="brand-mark">&lt;/&gt;</span> CODE ARENA <em>2026</em></Link><Card className="auth-card"><Badge>{register ? 'JOIN THE ARENA' : 'WELCOME BACK'}</Badge><h1>{register ? 'Create your competitor profile' : 'Sign in to Code Arena'}</h1><p>{register ? 'Your road to the championship starts here.' : 'Continue your championship campaign.'}</p><form onSubmit={submit}>{register && <><label>Display Name<input required name="name" placeholder="Your name" /></label><label>Username<input required name="username" placeholder="arena_handle" /></label></>}<label>Email Address<input required type="email" name="email" placeholder="you@example.com" /></label>{register && <label>Codeforces Username<input required name="codeforcesUsername" placeholder="tourist" /></label>}<label>Password<input required minLength={6} type="password" name="password" placeholder="••••••••" /></label>{register && <label className="check"><input required type="checkbox" /> I agree to the Code of Conduct</label>}{error && <p className="form-error">{error}</p>}<Button disabled={busy} type="submit">{busy ? 'Please wait...' : register ? 'Register Account' : 'Login'} <ArrowRight size={16} /></Button></form><p className="auth-switch">{register ? 'Already registered?' : 'New to the arena?'} <Link to={register ? '/login' : '/register'}>{register ? 'Login' : 'Register now'}</Link></p></Card></div>
}

function Dashboard() {
  const { user } = useAuth(); const { tournament, loading, error } = useTournament(); const [entries, setEntries] = useState<TournamentEntry[]>([])
  useEffect(() => { if (tournament) tournamentApi.leaderboard(tournament._id).then(({ leaderboard }) => setEntries(leaderboard)) }, [tournament])
  const own = entries.find((entry) => entry.participant.user._id === user?._id || entry.participant.user.id === user?.id)
  return <PageState loading={loading} error={error} empty={!tournament}><header className="page-heading"><div><small>PARTICIPANT DASHBOARD</small><h1>Welcome back, {user?.username}</h1><p><CheckCircle2 size={15} color="#00E676" /> Codeforces Synced</p></div><Badge tone={statusTone(tournament?.status) as 'blue'}>{tournament?.currentRound}</Badge></header><div className="stat-grid">{[['Current Rank', own?.latestRank ? `#${own.latestRank}` : '—'], ['Score', own?.score ?? 0], ['Penalty', own?.penalty ?? 0]].map(([label, value]) => <Card key={label}><small>{label}</small><strong className="stat-value">{value}</strong></Card>)}</div><div className="two-col"><Card><small>NEXT MATCH STATUS</small><h2>{tournament?.status === 'REGISTRATION' ? 'Registration is open' : tournament?.currentRound}</h2><p>Check the live contest and bracket for the official state.</p><Link to="/live">Open Live Contest <ArrowRight size={15} /></Link></Card><Card><small>RECENT CONTEST LOGS</small>{own?.latestRank ? <p>Rank #{own.latestRank} · {own.solved} solved · {own.score} pts</p> : <EmptyState label="No contest results yet." />}</Card></div></PageState>
}

function BracketPage() {
  const { tournament, loading, error } = useTournament(); const [bracket, setBracket] = useState<Bracket | null>(null)
  useEffect(() => { if (tournament) tournamentApi.bracket(tournament._id).then(({ bracket: data }) => setBracket(data)).catch(() => undefined) }, [tournament])
  const matchCard = (match: Bracket['quarterFinal'][number]) => <Card className="match" key={`${match.matchNumber}-${match.contest?._id}`}><small>MATCH {match.matchNumber}</small>{match.participants.map((participant) => <div className={match.winner?._id === participant._id ? 'match-player winner' : 'match-player'} key={participant._id}><span>{participant.user.username}</span>{match.winner?._id === participant._id && <Crown size={14} color="#FFD700" />}</div>)}<Badge tone={statusTone(match.contest?.status) as 'blue'}>{match.contest?.status || 'PENDING'}</Badge></Card>
  return <><Navbar /><main className="page public-page"><PageState loading={loading} error={error} empty={!tournament || !bracket}><header className="page-heading"><div><small>CODE ARENA 2026</small><h1>Championship Bracket</h1></div><Badge tone={statusTone(tournament?.status) as 'blue'}>{tournament?.status}</Badge></header><div className="bracket-scroll"><section className="bracket-column groups"><h3>GROUP STAGE</h3>{Object.entries(bracket?.groupStage || {}).map(([group, players]) => <Card key={group}><small>GROUP {group}</small>{players.length ? players.map((player) => <div className="match-player" key={player._id}><span>{player.seed && `#${player.seed} `}{player.user.username}</span><Badge tone={player.status === 'ELIMINATED' ? 'muted' : 'blue'}>{player.status}</Badge></div>) : <p>Awaiting draw</p>}</Card>)}</section><section className="bracket-column"><h3>QUARTER FINALS</h3>{(bracket?.quarterFinal || []).map(matchCard)}</section><section className="bracket-column"><h3>SEMIFINALS</h3>{(bracket?.semiFinal || []).map(matchCard)}</section><section className="bracket-column"><h3>GRAND FINAL</h3>{bracket?.final ? matchCard(bracket.final) : <EmptyState label="Finalists pending" />}<Card className="champion-card"><Crown color="#FFD700" /><small>CHAMPION</small><strong>{bracket?.champion?.user.username || 'To be crowned'}</strong></Card></section></div></PageState></main></>
}

function LeaderboardPage() {
  const { tournament, loading, error } = useTournament(); const [entries, setEntries] = useState<TournamentEntry[]>([]); const [query, setQuery] = useState(''); const [group, setGroup] = useState('ALL')
  useEffect(() => { if (tournament) tournamentApi.leaderboard(tournament._id).then(({ leaderboard }) => setEntries(leaderboard)).catch(() => undefined) }, [tournament])
  const filtered = useMemo(() => entries.filter((entry) => (group === 'ALL' || entry.group === group) && entry.participant.user.username.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (a.latestRank || 999) - (b.latestRank || 999)), [entries, group, query])
  return <><Navbar /><main className="page public-page"><PageState loading={loading} error={error} empty={!tournament}><header className="page-heading"><div><small>CHAMPIONSHIP STANDINGS</small><h1>Leaderboard</h1></div><div className="filters"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search competitor" /><select value={group} onChange={(event) => setGroup(event.target.value)}><option value="ALL">Overall</option>{['A', 'B', 'C', 'D'].map((item) => <option key={item}>Group {item}</option>)}</select></div></header><Leaderboard entries={filtered} /></PageState></main></>
}
function Leaderboard({ entries }: { entries: TournamentEntry[] }) { return <Card className="table-card"><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Participant</th><th>Group</th><th>Score</th><th>Solved</th><th>Penalty</th><th>Status</th></tr></thead><tbody>{entries.length ? entries.map((entry, index) => <tr key={entry.participant._id}><td><span className={`rank rank-${index + 1}`}>#{entry.latestRank || '—'}</span></td><td><strong>{entry.participant.user.username}</strong><small>{entry.participant.user.codeforcesUsername}</small></td><td>{entry.group || '—'}</td><td className="purple">{entry.score}</td><td>{entry.solved}</td><td>{entry.penalty}</td><td><Badge tone={statusTone(entry.status) as 'blue'}>{entry.status}</Badge></td></tr>) : <tr><td colSpan={7}><EmptyState label="No participant standings yet." /></td></tr>}</tbody></table></div></Card> }

function LivePage() {
  const { tournament, loading, error } = useTournament(); const [contests, setContests] = useState<Contest[]>([]); const [selected, setSelected] = useState<Contest | null>(null); const [entries, setEntries] = useState<LeaderboardEntry[]>([]); const [message, setMessage] = useState('')
  useEffect(() => { if (tournament) contestApi.list(tournament._id).then(({ contests: data }) => { setContests(data); setSelected(data.find((contest) => contest.status === 'LIVE') || data[0] || null) }).catch((err: Error) => setMessage(err.message)) }, [tournament])
  useEffect(() => { if (!tournament || !selected) return; let timer: number | undefined; const load = () => contestApi.leaderboard(tournament._id, selected._id).then(({ leaderboard }) => setEntries(leaderboard)).catch((err: Error) => setMessage(err.message)); load(); if (selected.status === 'LIVE') timer = window.setInterval(load, 15000); return () => { if (timer) window.clearInterval(timer) } }, [tournament, selected])
  return <><Navbar /><main className="page public-page"><PageState loading={loading} error={error} empty={!tournament}><header className="page-heading"><div><small><Radio size={14} color="#FF1744" /> LIVE SCOREBOARD</small><h1>{selected?.name || 'Live Contest'}</h1><p>Codeforces #{selected?.codeforcesContestId || '—'} · {selected?.durationMinutes || 0} minutes</p></div><Badge tone={statusTone(selected?.status) as 'blue'}>{selected?.status || 'NO CONTEST'}</Badge></header>{contests.length > 1 && <div className="contest-tabs">{contests.map((contest) => <button className={selected?._id === contest._id ? 'active' : ''} key={contest._id} onClick={() => setSelected(contest)}>{contest.name}</button>)}</div>}{message ? <ErrorState error={message} /> : <Card className="table-card"><p className="sync-label">Updates every 15 seconds while live.</p><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Participant</th><th>Solved</th><th>Penalty</th><th>Score</th></tr></thead><tbody>{entries.length ? entries.map((entry) => <tr key={entry.participantId}><td>#{entry.rank}</td><td><strong>{entry.username}</strong><small>{entry.codeforcesUsername}</small></td><td>{entry.solved}</td><td>{entry.penalty}</td><td className="purple">{entry.score}</td></tr>) : <tr><td colSpan={5}><EmptyState label="No matched Codeforces standings yet." /></td></tr>}</tbody></table></div></Card>}</PageState></main></>
}

function ContestPage({ results = false }: { results?: boolean }) {
  const { contestId } = useParams(); const { tournament, loading, error } = useTournament(); const [contest, setContest] = useState<Contest | null>(null); const [data, setData] = useState<Result[]>([]); const [loadError, setLoadError] = useState('')
  useEffect(() => { if (!tournament || !contestId) return; contestApi.list(tournament._id).then(({ contests }) => setContest(contests.find((item) => item._id === contestId) || null)); (results ? contestApi.results(tournament._id, contestId) : contestApi.results(tournament._id, contestId)).then(({ results: rows }) => setData(rows)).catch((err: Error) => setLoadError(err.message)) }, [tournament, contestId, results])
  return <><Navbar /><main className="page public-page"><PageState loading={loading} error={error || loadError} empty={!tournament}><header className="page-heading"><div><small>{contest?.round?.replace('_', ' ') || 'CONTEST'}</small><h1>{results ? 'Official Results' : contest?.name || 'Contest Details'}</h1><p>Codeforces #{contest?.codeforcesContestId || '—'} · Starts {formatDate(contest?.startTime)}</p></div>{contest && <a className="button secondary" target="_blank" href={contest.codeforcesUrl}>View on Codeforces <ExternalLink size={15} /></a>}</header><Card className="table-card"><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Participant</th><th>Solved</th><th>Penalty</th><th>Score</th><th>Result</th></tr></thead><tbody>{data.length ? data.map((item) => <tr key={item._id}><td>#{item.rank}</td><td><strong>{item.participant.user?.username || 'Participant'}</strong></td><td>{item.solved}</td><td>{item.penalty}</td><td className="purple">{item.score}</td><td><Badge tone={item.participant.status === 'ELIMINATED' ? 'muted' : 'green'}>{item.participant.status}</Badge></td></tr>) : <tr><td colSpan={6}><EmptyState label="Official results have not been synchronized." /></td></tr>}</tbody></table></div></Card></PageState></main></>
}

function ProfilePage() {
  const { participantId } = useParams(); const { tournament, loading, error } = useTournament(); const [participant, setParticipant] = useState<Participant | null>(null)
  useEffect(() => { if (tournament) tournamentApi.participants(tournament._id).then(({ participants }) => setParticipant(participants.find((item) => item._id === participantId) || null)) }, [tournament, participantId])
  return <><Navbar /><main className="page public-page"><PageState loading={loading} error={error} empty={!participant}><Card className="profile-card"><div className="avatar large">{participant?.user.username.slice(0, 1).toUpperCase()}</div><div><Badge tone={statusTone(participant?.status) as 'blue'}>{participant?.status || 'PARTICIPANT'}</Badge><h1>{participant?.user.username}</h1><p>Codeforces handle: <strong>{participant?.user.codeforcesUsername}</strong></p><p>Group {participant?.group || 'TBA'} · {participant?.currentRound}</p></div></Card><div className="stat-grid"><Card><small>TOURNAMENT STATUS</small><strong className="stat-value">{participant?.status}</strong></Card><Card><small>SEED</small><strong className="stat-value">#{participant?.seed || '—'}</strong></Card><Card><small>ROUND</small><strong className="stat-value">{participant?.currentRound}</strong></Card></div><Card><small>ACHIEVEMENTS</small><EmptyState label="No verified achievements are available yet." /></Card></PageState></main></>
}
function ChampionPage() {
  const { tournament, loading, error } = useTournament(); const [bracket, setBracket] = useState<Bracket | null>(null)
  useEffect(() => { if (tournament) tournamentApi.bracket(tournament._id).then(({ bracket: data }) => setBracket(data)) }, [tournament])
  return <><Navbar /><main className="page champion-page"><PageState loading={loading} error={error} empty={!tournament}>{tournament?.status !== 'COMPLETED' ? <EmptyState label="The champion will be revealed when the grand final is completed." /> : <><small>CHAMPIONSHIP GRAND FINAL MATCHUP</small><div className="final-line">{bracket?.final?.participants.map((participant) => <span key={participant._id}>{participant.user.username}</span>)}</div><Crown className="crown" size={72} color="#FFD700" /><small>CHAMPION REVEALED</small><h1>{bracket?.champion?.user.username}</h1><p>Code Arena 2026 Champion</p></>}</PageState></main></>
}

function AdminPage({ section = 'dashboard' }: { section?: 'dashboard' | 'participants' | 'groups' | 'contests' | 'bracket' | 'logs' }) {
  const location = useLocation(); const resolvedSection = location.pathname.endsWith('/logs') ? 'logs' : section; const { tournament, loading, error, setTournament } = useTournament(); const [participants, setParticipants] = useState<Participant[]>([]); const [contests, setContests] = useState<Contest[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const refresh = () => { if (!tournament) return; tournamentApi.get(tournament._id).then(({ tournament: current }) => setTournament(current)); tournamentApi.participants(tournament._id).then(({ participants: rows }) => setParticipants(rows)); contestApi.list(tournament._id).then(({ contests: rows }) => setContests(rows)) }
  useEffect(refresh, [tournament?._id])
  const act = async (action: 'start' | 'group-stage' | 'quarter-final' | 'semi-final' | 'complete') => { if (!tournament || !window.confirm('Are you sure you want to change tournament progression?')) return; setBusy(true); setMessage(''); try { if (action === 'start') await tournamentApi.start(tournament._id); else await tournamentApi.advance(tournament._id, action); setMessage('Tournament updated successfully.'); refresh() } catch (err) { setMessage(err instanceof Error ? err.message : 'Action failed') } finally { setBusy(false) } }
  const sync = async (contest: Contest) => { if (!tournament) return; setBusy(true); try { const response = await contestApi.sync(tournament._id, contest._id); setMessage(`Synchronized ${response.results.length} results. ${response.unmatchedHandles.length} unmatched handles.`); refresh() } catch (err) { setMessage(err instanceof Error ? err.message : 'Sync failed') } finally { setBusy(false) } }
  return <PageState loading={loading} error={error} empty={!tournament}><header className="page-heading"><div><small>ADMINISTRATION</small><h1>{resolvedSection === 'dashboard' ? 'Control Center' : resolvedSection === 'groups' ? 'Groups & Seeding' : resolvedSection[0].toUpperCase() + resolvedSection.slice(1)}</h1><p>Active Season: {tournament?.name}</p></div><Badge tone={statusTone(tournament?.status) as 'blue'}>{tournament?.status}</Badge></header>{message && <p className="admin-message">{message}</p>}{resolvedSection === 'dashboard' && <><div className="stat-grid">{[['Total Competitors', participants.length], ['Active Contests', contests.filter((contest) => contest.status === 'LIVE').length], ['Current Stage', tournament?.currentRound || '—']].map(([name, value]) => <Card key={String(name)}><small>{name}</small><strong className="stat-value">{value}</strong></Card>)}</div><Card><small>TOURNAMENT PROGRESSION</small><div className="admin-actions"><Button disabled={busy || tournament?.status !== 'REGISTRATION'} onClick={() => act('start')}>Start Tournament</Button><Button disabled={busy || tournament?.status !== 'GROUP_STAGE'} onClick={() => act('group-stage')}>Advance Group Stage</Button><Button disabled={busy || tournament?.status !== 'QUARTER_FINAL'} onClick={() => act('quarter-final')}>Advance Quarter Final</Button><Button disabled={busy || tournament?.status !== 'SEMI_FINAL'} onClick={() => act('semi-final')}>Advance Semi Final</Button><Button disabled={busy || tournament?.status !== 'FINAL'} onClick={() => act('complete')}>Complete Tournament</Button></div></Card></>}{resolvedSection === 'participants' && <Leaderboard entries={participants.map((participant) => ({ participant, group: participant.group, currentRound: participant.currentRound, status: participant.status, latestRank: null, solved: 0, score: 0, penalty: 0 }))} />}{resolvedSection === 'groups' && <GroupAdmin tournamentId={tournament!._id} />}{resolvedSection === 'contests' && <AdminContests tournament={tournament!} />}{resolvedSection === 'bracket' && <BracketPage />}{resolvedSection === 'logs' && <AdminLogs tournamentId={tournament!._id} />}</PageState>
}
function GroupAdmin({ tournamentId }: { tournamentId: string }) { const [groups, setGroups] = useState<Record<string, Participant[]>>({}); useEffect(() => { tournamentApi.groups(tournamentId).then(({ groups: data }) => setGroups(data)) }, [tournamentId]); return <div className="group-grid">{['A', 'B', 'C', 'D'].map((group) => <Card key={group}><small>GROUP {group}</small>{(groups[group] || []).length ? groups[group].map((participant) => <div className="match-player" key={participant._id}>#{participant.seed} {participant.user.username}</div>) : <EmptyState label="Groups will appear after the draw." />}</Card>)}</div> }

function Protected({ admin = false }: { admin?: boolean }) { const { user, loading } = useAuth(); if (loading) return <LoadingState />; if (!user) return <Navigate to="/login" replace />; if (admin && user.role !== 'ADMIN') return <Navigate to="/dashboard" replace />; return <DashboardLayout admin={admin} /> }
function App() { return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/bracket" element={<BracketPage />} /><Route path="/leaderboard" element={<LeaderboardPage />} /><Route path="/live" element={<LivePage />} /><Route path="/contests/:contestId" element={<ContestPage />} /><Route path="/results/:contestId" element={<ContestPage results />} /><Route path="/participants/:participantId" element={<ProfilePage />} /><Route path="/champion" element={<ChampionPage />} /><Route element={<Protected />}><Route path="/dashboard" element={<Dashboard />} /></Route><Route element={<Protected admin />}><Route path="/admin" element={<AdminPage />} /><Route path="/admin/participants" element={<AdminPage section="participants" />} /><Route path="/admin/groups" element={<AdminPage section="groups" />} /><Route path="/admin/contests" element={<AdminPage section="contests" />} /><Route path="/admin/results" element={<AdminPage section="contests" />} /><Route path="/admin/bracket" element={<AdminPage section="bracket" />} /><Route path="/admin/logs" element={<AdminPage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter></AuthProvider> }
export default App
